### ISSUE TITLE
CSS Review

### ISSUE THREAD

**Issue by jordanwillis** [sarahisnorm/prj-rev-bwfs-dasmoto#2]
Similarly, your CSS looks great as well!  Typically I recommend students to pay attention to repeated styles, but you took care of that by combining elements together in a single rule.

```
h1, 
h2, 
h3, 
p {
  font-family: "Helvetica", sans-serif;
}
```

As you continue practicing with CSS, keep up the good work ensuring you are following the DRY (don't repeat yourself) principle (like you have demonstrated on this project).

**Comment by sarahisnorm** [comment]
Thanks Jordan.  I like a good acronym and will keep a note of the DRY principle.
