### ISSUE TITLE
Summary: Grade = Exceeds Expectations

### ISSUE THREAD

**Issue by jordanwillis** [sarahisnorm/prj-rev-bwfs-dasmoto#3]
Nice work on your project!  As I mentioned earlier, I really liked how you applied good style best practices and used correct indentation in your HTML and CSS.  This seemingly trivial detail plays a bit part in overall code readability, which becomes really important on large projects or projects with many contributors.

Your CSS is also designed appropriately, and the only feedback that I would give is to consider creating a specific class for your base `h2` styles used in the brushes, frames, and paint sections.  Something like this:

```
.item h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
  padding-top: 5px;
}
```

And then using that class in your HTML...

```
<div class="item">
  <h2 id="frame">Frames</h2>
  <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/frames.jpeg"/>
  <h3>Art Frames (assorted)</h3>
  <p>Assorted frames made of different material, including MDF, birchwood, and PDE. Select frames can be sanded and painted according to your needs. <span class="price">Starting at $2.00 / frame.</span></p>
</div>
```

I make this recommendation because you can often run into confusion or trouble when setting default element styles (especially if you have multiple default styles spread across different rulesets).

https://github.com/sarahisnorm/prj-rev-bwfs-dasmoto/blob/master/dasmotos/resources/css/style.css#L2
https://github.com/sarahisnorm/prj-rev-bwfs-dasmoto/blob/master/dasmotos/resources/css/style.css#L18

You can hopefully imagine what it might be like managing this on a large website with hundreds of lines of CSS.  Using class names to provide extra semantics just helps keep your styling intentions organized.

Of course, this feedback is really only relevant for the future as the way you implemented it on this project was perfectly fine.

Keep up the good work!

**Comment by sarahisnorm** [comment]
Thanks Jordan! I appreciate the info on how to work on a larger scale, when you have repeating styles for different sections.  Much easier than trying to remember multiple IDs, as I had used in this project. Cheers!
